/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    media: Media;
    submissions: Submission;
    'news-candidates': NewsCandidate;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'news-candidates': NewsCandidatesSelect<false> | NewsCandidatesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  penName?: string | null;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于未来个人页面网址，只使用小写英文字母、数字和短横线。
   */
  slug: string;
  status: 'active' | 'paused' | 'archived';
  region?: string | null;
  literaryIdentities?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  organizations?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  biography?: string | null;
  /**
   * 这里只是预留内容；本阶段不会公开显示。
   */
  publicBiography?: string | null;
  representativeWorks?:
    | {
        title: string;
        type?: string | null;
        year?: number | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 供未来新闻搜索使用，本阶段不会自动搜索。
   */
  searchKeywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  websites?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  knownWeChatAccounts?:
    | {
        name: string;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  profileImage?: (number | null) | Media;
  displayOrder?: number | null;
  /**
   * 只有本人同意后才能开启；本阶段仍不会生成公开页面。
   */
  publicProfileEnabled?: boolean | null;
  disabilityCategory?:
    | ('physical' | 'visual' | 'hearing' | 'speech' | 'intellectual' | 'mental' | 'multiple' | 'other' | 'notProvided')
    | null;
  disabilityLevel?: ('level1' | 'level2' | 'level3' | 'level4' | 'notProvided') | null;
  showDisabilityCategory?: boolean | null;
  showDisabilityLevel?: boolean | null;
  consentStatus: 'notRequested' | 'granted' | 'denied';
  consentDate?: string | null;
  consentNotes?: string | null;
  /**
   * 仅供后台使用，未来公开页面不得读取。
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 简要描述图片内容，方便使用读屏软件的读者理解。
   */
  alt: string;
  /**
   * 请勿上传证件、授权书扫描件或其他敏感证明材料。
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  submissionNumber: string;
  submittedAt: string;
  submitterName: string;
  penName?: string | null;
  /**
   * 仅供编辑联系投稿人，不得公开。
   */
  contact: string;
  title: string;
  category: 'poetry' | 'fiction' | 'prose' | 'criticism' | 'other';
  content: string;
  notes?: string | null;
  rightsConfirmed: boolean;
  status: 'submitted' | 'reviewing' | 'revisionRequested' | 'accepted' | 'rejected';
  /**
   * 由管理员审核后选择，公开投稿页不会显示成员名单。
   */
  relatedMember?: (number | null) | Member;
  /**
   * 仅后台可见，不会向投稿人或公开页面展示。
   */
  reviewNotes?: string | null;
  requestToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-candidates".
 */
export interface NewsCandidate {
  id: number;
  candidateNumber: string;
  title: string;
  /**
   * 请核对身份后再关联，不能只凭姓名相同判断。
   */
  relatedMember?: (number | null) | Member;
  /**
   * 尚未确认对应成员时，可以先记录来源中的姓名。
   */
  relatedPersonName?: string | null;
  category: 'creation' | 'award' | 'activity' | 'media' | 'personal' | 'other';
  /**
   * 只保存必要的核实信息，不要复制整篇来源文章或无关隐私。
   */
  summary?: string | null;
  publishedAt?: string | null;
  /**
   * 本阶段只使用“管理员手工录入”；另外两项仅为以后预留。
   */
  sourceType: 'manual' | 'publicTip' | 'automaticSearch';
  sourceName?: string | null;
  /**
   * 只填写以 http:// 或 https:// 开头的公开来源网址。
   */
  sourceUrl?: string | null;
  /**
   * 供后续线索或自动搜索程序使用，当前手工录入可以留空。
   */
  sourceReference?: string | null;
  discoveredAt: string;
  /**
   * 新闻候选未经人工核实不得发布；“已确认”不代表已经对外发布。
   */
  status: 'pending' | 'verifying' | 'confirmed' | 'rejected' | 'duplicate';
  /**
   * 仅后台可见，请记录来源核对过程和需要注意的问题。
   */
  verificationNotes?: string | null;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'news-candidates';
        value: number | NewsCandidate;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  penName?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  slug?: T;
  status?: T;
  region?: T;
  literaryIdentities?:
    | T
    | {
        value?: T;
        id?: T;
      };
  organizations?:
    | T
    | {
        value?: T;
        id?: T;
      };
  biography?: T;
  publicBiography?: T;
  representativeWorks?:
    | T
    | {
        title?: T;
        type?: T;
        year?: T;
        notes?: T;
        id?: T;
      };
  searchKeywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  websites?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  knownWeChatAccounts?:
    | T
    | {
        name?: T;
        notes?: T;
        id?: T;
      };
  profileImage?: T;
  displayOrder?: T;
  publicProfileEnabled?: T;
  disabilityCategory?: T;
  disabilityLevel?: T;
  showDisabilityCategory?: T;
  showDisabilityLevel?: T;
  consentStatus?: T;
  consentDate?: T;
  consentNotes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  submissionNumber?: T;
  submittedAt?: T;
  submitterName?: T;
  penName?: T;
  contact?: T;
  title?: T;
  category?: T;
  content?: T;
  notes?: T;
  rightsConfirmed?: T;
  status?: T;
  relatedMember?: T;
  reviewNotes?: T;
  requestToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-candidates_select".
 */
export interface NewsCandidatesSelect<T extends boolean = true> {
  candidateNumber?: T;
  title?: T;
  relatedMember?: T;
  relatedPersonName?: T;
  category?: T;
  summary?: T;
  publishedAt?: T;
  sourceType?: T;
  sourceName?: T;
  sourceUrl?: T;
  sourceReference?: T;
  discoveredAt?: T;
  status?: T;
  verificationNotes?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}